### ISSUE TITLE
undefined: httpcache.Service?

### ISSUE THREAD

**Issue by xpbliss** [GeekyPanda/mono#2]
- Version : **0.0.1**

- Operating System:

- [x] I have read the [contributing file](https://github.com/kataras/iris/blob/master/.github/CONTRIBUTING.md) and I'm sure that this issue is not posted & answered before.

--------------
when i run the  ```main.go```, the errors is the following:
```github.com\geekypanda\mono\mono.go:94: undefined: httpcache.Service```

**Comment by GeekyPanda** [comment]
Mono is not ready yet, as title says, please check at 15-20 days from now

**Comment by xpbliss** [comment]
I think you should throew out  the fasthttp suppor , because the iris is the best .   
And  you should only support net/http,the go native net/http.

**Comment by GeekyPanda** [comment]
@xpbliss Mono **is not ready yet** and it supports **only net/http** I really cannot understand you, why you ask many times the same thing?

**Comment by xpbliss** [comment]
New release?
